#!/usr/bin/env bash

source ./env

echo "Building metad linux version ..."
mkdir -p bin/linux/
env GOOS=linux GOARCH=amd64 go build -o bin/linux/metad .
ls -lh bin/linux/


echo "Building metad darwin version ..."
mkdir -p bin/darwin/
env GOOS=darwin GOARCH=amd64 go build -o bin/darwin/metad .
ls -lh bin/darwin/
