#!/usr/bin/env bash
# Copyright 2018 Yunify Inc. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

source ./env

OUTPUT=${1:-bin/metad}

gen_version

echo "Building metad ..."
mkdir -p bin
go build -o $OUTPUT .

revert_version
