#!/usr/bin/env bash

source ./env

echo "Release metad linux version ..."
mkdir -p bin/linux
env GOOS=linux GOARCH=amd64 go build -o bin/linux/metad-linux-amd64 .


echo "Release metad darwin version ..."
mkdir -p bin/drawin
env GOOS=darwin GOARCH=amd64 go build -o bin/darwin/metad-darwin-amd64 .

ls -lh bin/*
