#!/usr/bin/env bash

source ./env

gen_version

echo "Release metad linux version ..."
mkdir -p bin/linux
env GOOS=linux GOARCH=amd64 go build -o bin/linux/metad .
tar -C bin/linux/ -czf bin/linux/metad-linux-amd64.tar.gz metad

echo "Release metad darwin version ..."
mkdir -p bin/darwin
env GOOS=darwin GOARCH=amd64 go build -o bin/darwin/metad .
tar -C bin/darwin/ -czf bin/darwin/metad-darwin-amd64.tar.gz metad

ls -lh bin/*

revert_version
