#!/usr/bin/env bash
# Copyright 2018 Yunify Inc. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

source ./env

IGNORE_PKGS="(vendor)"
TEST_PKGS=`find . -name \*_test.go | while read a; do dirname $a; done | sort | uniq | egrep -v "$IGNORE_PKGS" | sed "s|\./||g"`
INTEGRATION_PKGS="(integration|contrib)"
COVER=${COVER:-"-cover"}
TESTABLE=`echo "$TEST_PKGS" | egrep -v "$INTEGRATION_PKGS"`

if [ -z "$PKG" ]; then
	TEST=$TESTABLE
else
	# strip out leading dotslashes and trailing slashes from PKG=./foo/
	TEST=${PKG/#./}
	TEST=${TEST/#\//}
	TEST=${TEST/%\//}
fi

# split TEST into an array and prepend REPO_PATH to each local package
split=(${TEST// / })
TEST=${split[@]/#/${REPO_PATH}/}

echo "Running tests... ${TEST}"
#--race -cpu 1,2,4
go test --race --cpu 1,2,4 -timeout 5m ${COVER} -run=Test $@ ${TEST}
